"""empty message

Revision ID: 4711e739ef73
Revises: 1806eaaadac5
Create Date: 2014-08-26 15:43:54.430000

"""

# revision identifiers, used by Alembic.
revision = '4711e739ef73'
down_revision = '1806eaaadac5'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###
